name: Build only (sin tests)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Cachear gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Instalar gems
        run: bundle install --jobs=4 --retry=3

      # 6. Preparar base de datos de desarrollo
      - name: Preparar DB de desarrollo
        env:
          RAILS_ENV: development
        run: |
          unset DATABASE_URL
          bundle exec rails db:drop db:create db:schema:load

      - name: Precompilar assets
        run: |
          bundle exec rails assets:precompile
