name: Rails tests (SQLite)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Cachear gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Instalar gems
        run: bundle install --jobs=4 --retry=3

      - name: Preparar DB de test
        env:
          RAILS_ENV: test
        run: |
          unset DATABASE_URL
          # 1) Fija el entorno dentro de structure.sql
          bundle exec rails db:environment:set RAILS_ENV=test
          # 2) Carga el esquema SQL (structure.sql) en SQLite3
          bundle exec rails db:drop db:create db:structure:load

      - name: Ejecutar la suite de tests
        env:
          RAILS_ENV: test
        run: |
          unset DATABASE_URL
          bundle exec rails test
