name: Rails tests (SQLite)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev

    - name: Cachear gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Instalar gems
      run: bundle install --jobs=4 --retry=3

    - name: Preparar DB de test
      env:
        RAILS_ENV: test
        DATABASE_URL: ""      # fuerza SQLite
      run: |
        bin/rails db:drop db:create db:schema:load

    - name: Ejecutar test suite
      env:
        RAILS_ENV: test
        DATABASE_URL: ""
      run: bundle exec rails test
